//! DEC-320 v1 — `phg build --php` (split sibling emission + shared runtime).
//!
//! Two gates: a pure-Rust structural check (siblings + runtime + classmap + idempotence) that
//! always runs, and a behavior check driving the generated output under a REAL host `php` with
//! composer-style wiring (`files`-loaded runtime + its classmap autoloader), asserting the host
//! run is byte-identical to `phg run`. PHP gating mirrors the differential oracle:
//! `PHORJ_REQUIRE_PHP=1` makes a missing `php` FAIL (CI), otherwise it skips loudly.

use std::path::{Path, PathBuf};
use std::process::Command;

const BIN: &str = env!("CARGO_BIN_EXE_phg");

/// Copy the committed multi-package fixture into a scratch dir (the build writes siblings; the
/// repo tree must stay clean).
fn scratch_shapes(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("phorj_build_php_{tag}_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    copy_tree(Path::new("examples/project/shapes"), &dir);
    dir
}

fn copy_tree(from: &Path, to: &Path) {
    std::fs::create_dir_all(to).expect("mkdir");
    for e in std::fs::read_dir(from).expect("read_dir") {
        let e = e.expect("entry");
        let dst = to.join(e.file_name());
        if e.file_type().expect("ft").is_dir() {
            copy_tree(&e.path(), &dst);
        } else {
            std::fs::copy(e.path(), &dst).expect("copy");
        }
    }
}

fn build_php(entry: &Path) -> String {
    let out = Command::new(BIN)
        .args(["build", entry.to_str().unwrap(), "--php"])
        .output()
        .expect("spawn phg");
    assert!(
        out.status.success(),
        "build --php failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout).expect("utf-8")
}

#[test]
fn split_build_emits_siblings_runtime_classmap_and_is_idempotent() {
    let dir = scratch_shapes("struct");
    let entry = dir.join("src/main.phg");
    let first = build_php(&entry);
    // Every type-declaring .phg gains a sibling; the shared runtime appears once.
    for sib in [
        "src/Acme/Geometry/Shape.php",
        "src/Acme/Geometry/Rect.php",
        "src/Acme/Geometry/Paint.php",
        "src/_phorj/runtime.php",
    ] {
        assert!(dir.join(sib).exists(), "missing {sib}\n{first}");
    }
    // The one-time composer diff is printed on the run that creates the runtime.
    assert!(first.contains("\"files\""), "{first}");
    let runtime = std::fs::read_to_string(dir.join("src/_phorj/runtime.php")).expect("runtime");
    // Free functions live in the runtime (PHP never autoloads functions)…
    assert!(runtime.contains("function main"), "{runtime}");
    // …and the classmap covers the enum's SEVERAL classes per file (plain PSR-4 cannot).
    for fqn in [
        "'Acme\\\\Geometry\\\\Paint_Green'",
        "'Acme\\\\Geometry\\\\Rect'",
    ] {
        assert!(runtime.contains(fqn), "classmap missing {fqn}\n{runtime}");
    }
    // The siblings carry the generated-file marker and NO helpers/bootstrap.
    let rect = std::fs::read_to_string(dir.join("src/Acme/Geometry/Rect.php")).expect("rect");
    assert!(rect.contains("@generated by phg build --php"), "{rect}");
    assert!(!rect.contains("__phorj_checked_add($a, $b) {"), "{rect}");
    assert!(!rect.contains("\\Main\\main();"), "{rect}");
    // Idempotence: a second build writes NOTHING (content compare).
    let second = build_php(&entry);
    assert!(
        second.contains("0 file(s) written"),
        "second build not a no-op:\n{second}"
    );
    let _ = std::fs::remove_dir_all(&dir);
}

/// Resolve the php binary — the differential oracle's gating (self-contained per test file).
fn php_bin() -> Option<String> {
    if std::env::var("PHORJ_SKIP_PHP").as_deref() == Ok("1") {
        return None;
    }
    let cand = std::env::var("PHORJ_PHP").unwrap_or_else(|_| "php".to_string());
    let ok = Command::new(&cand)
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false);
    if ok {
        return Some(cand);
    }
    assert!(
        std::env::var("PHORJ_REQUIRE_PHP").as_deref() != Ok("1"),
        "PHORJ_REQUIRE_PHP=1 but no php available"
    );
    eprintln!("SKIP (loud): no `php` on PATH — build --php host-parity leg not verified here");
    None
}

#[test]
fn split_build_output_matches_phg_run_under_host_php() {
    let Some(php) = php_bin() else { return };
    let dir = scratch_shapes("parity");
    let entry = dir.join("src/main.phg");
    build_php(&entry);
    // The composer-style host: `files` loads the runtime (whose classmap autoloader lazy-loads
    // every sibling class), then the host calls the phorj entry as a plain callable.
    let host = dir.join("host.php");
    std::fs::write(
        &host,
        "<?php\nrequire __DIR__ . '/src/_phorj/runtime.php';\n\\Main\\main();\n",
    )
    .expect("write host");
    let host_out = Command::new(&php).arg(&host).output().expect("spawn php");
    assert!(
        host_out.status.success(),
        "host php failed: {}",
        String::from_utf8_lossy(&host_out.stderr)
    );
    let run_out = Command::new(BIN)
        .args(["run", entry.to_str().unwrap()])
        .output()
        .expect("spawn phg run");
    assert!(run_out.status.success());
    assert_eq!(
        String::from_utf8_lossy(&host_out.stdout),
        String::from_utf8_lossy(&run_out.stdout),
        "host-php split output ≠ phg run"
    );
    let _ = std::fs::remove_dir_all(&dir);
}
