//! DEC-320 v1 — `phg build --php <entry>`: the compile-time adoption lever (TS→JS playbook).
//!
//! Transpiles every project item into the `.php` SIBLING of the `.phg` that declared it (PSR-4
//! addressing unchanged — zero composer.json edits for the class files) plus ONE shared
//! `_phorj/runtime.php` (helpers + injected preludes + free functions + static inits; see
//! [`crate::transpile::split`]). The only composer touch is the `files` autoload entry for the
//! runtime — printed as a diff for the user to apply BY HAND (phg never edits composer.json; the
//! same hand-the-command discipline as everything else that mutates foreign state).
//!
//! Idempotent: a sibling whose generated content is unchanged is SKIPPED (content compare — no
//! mtime races), so repeated builds are clean no-ops and CI can diff-check with `git status`.

use super::pipeline::on_deep_stack;
use std::path::{Path, PathBuf};

/// The first-line marker every generated sibling carries (after `<?php`), so humans and tools
/// (`.gitattributes` `linguist-generated`) can tell generated output from hand-written PHP.
const GENERATED_MARKER: &str =
    "/* @generated by phg build --php — edit the .phg source, not this file */";

/// Run the split build for a loaded project. Returns the human summary (one line per file written
/// or skipped, the runtime path, and the one-time composer diff when the runtime is new).
pub fn cmd_build_php(entry: &Path, unit: &crate::loader::Unit) -> Result<String, String> {
    let split = on_deep_stack(|| {
        super::pipeline::reject_native_only_transpile(&unit.program)?;
        let checked = super::pipeline::check_and_expand(&unit.program, &unit.diag_src)?;
        // A single-file (loose) load carries no attribution map — every user item then belongs to
        // the entry file itself (its sibling), and only helpers/preludes go to the runtime.
        let item_files = if unit.item_files.is_empty() {
            let mut m = std::collections::HashMap::new();
            for item in &unit.program.items {
                let name = match item {
                    crate::ast::Item::Class(c) if !c.foreign => &c.name,
                    crate::ast::Item::Enum(e) => &e.name,
                    crate::ast::Item::Interface(i) => &i.name,
                    crate::ast::Item::Trait(t) => &t.name,
                    crate::ast::Item::Function(f) if !f.foreign => &f.name,
                    _ => continue,
                };
                m.insert(name.clone(), entry.to_path_buf());
            }
            m
        } else {
            unit.item_files.clone()
        };
        crate::transpile::split::emit_split(&checked, &item_files)
    })?;
    let mut out = String::new();
    let mut written = 0usize;
    let mut current = 0usize;
    for (phg, php) in &split.files {
        let sibling = phg.with_extension("php");
        let body = with_marker(php);
        match write_if_changed(&sibling, &body)? {
            true => {
                written += 1;
                out.push_str(&format!("wrote   {}\n", sibling.display()));
            }
            false => {
                current += 1;
                out.push_str(&format!("current {}\n", sibling.display()));
            }
        }
    }
    // The shared runtime sits beside the entry file, under `_phorj/` (gitignore or commit — the
    // team's policy; both work).
    let runtime_dir = entry
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join("_phorj");
    let runtime_path = runtime_dir.join("runtime.php");
    let runtime_is_new = !runtime_path.exists();
    std::fs::create_dir_all(&runtime_dir)
        .map_err(|e| format!("build --php: cannot create {}: {e}", runtime_dir.display()))?;
    // The generated classmap autoloader: the runtime registers it, so every sibling class —
    // including an enum's several classes per file, which plain PSR-4 cannot address — lazy-loads
    // with NO host composer wiring beyond the one `files` entry. Paths are relative to the
    // runtime's own directory (portable checkouts).
    let entry_dir = entry.parent().unwrap_or_else(|| Path::new("."));
    let mut map_rows = String::new();
    for (fqn, phg) in &split.classmap {
        let sibling = phg.with_extension("php");
        let rel = sibling.strip_prefix(entry_dir).unwrap_or(&sibling);
        let rel = rel.to_string_lossy().replace('\\', "/");
        let esc = fqn.replace('\\', "\\\\");
        map_rows.push_str(&format!("        '{esc}' => '/../{rel}',\n"));
    }
    let register = format!(
        "spl_autoload_register(function ($c) {{\n    static $m = [\n{map_rows}    ];\n    \
         if (isset($m[$c])) {{ require __DIR__ . $m[$c]; }}\n}});\n"
    );
    // Brace-namespace output forbids top-level code outside `namespace {}` — wrap accordingly.
    let autoloader = if split.namespaced {
        format!("namespace {{\n{register}}}\n")
    } else {
        register
    };
    let runtime_body = with_marker(&format!("{}{autoloader}", split.runtime));
    if write_if_changed(&runtime_path, &runtime_body)? {
        written += 1;
        out.push_str(&format!("wrote   {}\n", runtime_path.display()));
    } else {
        current += 1;
        out.push_str(&format!("current {}\n", runtime_path.display()));
    }
    out.push_str(&format!(
        "{written} file(s) written, {current} already current\n"
    ));
    if runtime_is_new {
        out.push_str(&format!(
            "\nRegister the shared runtime ONCE in the host composer.json (phg never edits it):\n\
             \n    \"autoload\": {{\n        \"files\": [\"{}\"]\n    }}\n\
             \nthen `composer dump-autoload`. Class files need NO composer change (PSR-4 siblings).\n",
            runtime_path.display()
        ));
    }
    Ok(out)
}

/// Insert the generated-file marker as the first line after `<?php`.
fn with_marker(php: &str) -> String {
    match php.strip_prefix("<?php\n") {
        Some(rest) => format!("<?php\n{GENERATED_MARKER}\n{rest}"),
        None => format!("{GENERATED_MARKER}\n{php}"),
    }
}

/// Write `body` to `path` unless the current content is already identical (content compare — the
/// skip-if-current contract). Returns whether a write happened.
fn write_if_changed(path: &PathBuf, body: &str) -> Result<bool, String> {
    if let Ok(existing) = std::fs::read_to_string(path) {
        if existing == *body {
            return Ok(false);
        }
    }
    std::fs::write(path, body)
        .map_err(|e| format!("build --php: cannot write {}: {e}", path.display()))?;
    Ok(true)
}
