//! The unboxed helper-table STRUCTS (M-Decomp, Invariant 13): [`UbHelperIds`] — the per-module
//! declared `FuncId`s — and [`UbHelperRefs`] — the same set imported into one function body.
//! Field lists stay in lockstep with `handles/symbols.rs`, the `compile.rs` declares, and
//! `emit_unboxed/refs.rs` (the Ids→Refs import).

use cranelift::codegen::ir::FuncRef;
use cranelift_module::FuncId;

/// The declared import ids of the handle-op helpers (one per `JITModule`, when the graph uses
/// handles); [`UbHelperRefs`] is the same set declared into one function body.
pub(in crate::jit) struct UbHelperIds {
    pub(in crate::jit) list_new: FuncId,
    pub(in crate::jit) list_push: FuncId,
    pub(in crate::jit) list_seal: FuncId,
    pub(in crate::jit) index: FuncId,
    pub(in crate::jit) concat: FuncId,
    pub(in crate::jit) str_len: FuncId,
    pub(in crate::jit) free: FuncId,
    pub(in crate::jit) map_push_pair: FuncId,
    pub(in crate::jit) map_seal: FuncId,
    pub(in crate::jit) set_seal: FuncId,
    pub(in crate::jit) map_get: FuncId,
    pub(in crate::jit) map_has: FuncId,
    pub(in crate::jit) list_push_int: FuncId,
    pub(in crate::jit) index_int: FuncId,
    pub(in crate::jit) int_to_str: FuncId,
    pub(in crate::jit) concat_mix: FuncId,
    pub(in crate::jit) acc_append: FuncId,
    pub(in crate::jit) list_len: FuncId,
    pub(in crate::jit) list_acc_append: FuncId,
    pub(in crate::jit) map_builder_set: FuncId,
    pub(in crate::jit) map_builder_seed: FuncId,
    pub(in crate::jit) list_acc_reseed: FuncId,
    pub(in crate::jit) list_builder_new: FuncId,
    pub(in crate::jit) list_append_clone: FuncId,
    pub(in crate::jit) native2: FuncId,
    pub(in crate::jit) str_eq: FuncId,
    pub(in crate::jit) clone_value: FuncId,
    pub(in crate::jit) list_append_dyn: FuncId,
    pub(in crate::jit) str_list_acc_append: FuncId,
    pub(in crate::jit) map_keys: FuncId,
    pub(in crate::jit) map_values: FuncId,
    pub(in crate::jit) map_merge: FuncId,
    pub(in crate::jit) map_size: FuncId,
    pub(in crate::jit) map_ext_new: FuncId,
    pub(in crate::jit) map_ext_push: FuncId,
    pub(in crate::jit) str_contains: FuncId,
    pub(in crate::jit) validate: FuncId,
    pub(in crate::jit) set_diff: FuncId,
    pub(in crate::jit) set_union: FuncId,
}

pub(in crate::jit) struct UbHelperRefs {
    pub(in crate::jit) list_new: FuncRef,
    pub(in crate::jit) list_push: FuncRef,
    pub(in crate::jit) list_seal: FuncRef,
    pub(in crate::jit) index: FuncRef,
    pub(in crate::jit) concat: FuncRef,
    pub(in crate::jit) str_len: FuncRef,
    pub(in crate::jit) free: FuncRef,
    pub(in crate::jit) map_push_pair: FuncRef,
    pub(in crate::jit) map_seal: FuncRef,
    pub(in crate::jit) set_seal: FuncRef,
    pub(in crate::jit) map_get: FuncRef,
    pub(in crate::jit) map_has: FuncRef,
    pub(in crate::jit) list_push_int: FuncRef,
    pub(in crate::jit) index_int: FuncRef,
    pub(in crate::jit) int_to_str: FuncRef,
    pub(in crate::jit) concat_mix: FuncRef,
    pub(in crate::jit) acc_append: FuncRef,
    pub(in crate::jit) list_len: FuncRef,
    pub(in crate::jit) list_acc_append: FuncRef,
    pub(in crate::jit) map_builder_set: FuncRef,
    pub(in crate::jit) map_builder_seed: FuncRef,
    pub(in crate::jit) list_acc_reseed: FuncRef,
    pub(in crate::jit) list_builder_new: FuncRef,
    pub(in crate::jit) list_append_clone: FuncRef,
    pub(in crate::jit) native2: FuncRef,
    pub(in crate::jit) str_eq: FuncRef,
    pub(in crate::jit) clone_value: FuncRef,
    pub(in crate::jit) list_append_dyn: FuncRef,
    pub(in crate::jit) str_list_acc_append: FuncRef,
    pub(in crate::jit) map_keys: FuncRef,
    pub(in crate::jit) map_values: FuncRef,
    pub(in crate::jit) map_merge: FuncRef,
    pub(in crate::jit) map_size: FuncRef,
    pub(in crate::jit) map_ext_new: FuncRef,
    pub(in crate::jit) map_ext_push: FuncRef,
    pub(in crate::jit) str_contains: FuncRef,
    pub(in crate::jit) validate: FuncRef,
    pub(in crate::jit) set_diff: FuncRef,
    pub(in crate::jit) set_union: FuncRef,
}
