//! The Phorj keyword set surfaced in completion (CompletionItemKind 14 = Keyword). Not exhaustive of
//! every contextual word (`foreach`/`is`/`as`/`when` stay ordinary identifiers in the token stream and
//! are recognized positionally by the parser), but the structural keywords a user types most. Kept in
//! step with the reserved table in `crate::tokenizer` — a keyword highlighted by the grammar but absent
//! here is drift (Invariant 17).

pub(super) const KEYWORDS: &[&str] = &[
    "package",
    "import",
    "function",
    "class",
    "enum",
    "interface",
    "trait",
    "type",
    "constructor",
    "declare",
    "return",
    "if",
    "else",
    "for",
    "while",
    "do",
    "in",
    "match",
    "when",
    "var",
    "mutable",
    "static",
    "const",
    "open",
    "abstract",
    "sealed",
    "public",
    "private",
    "protected",
    "internal",
    "new",
    "this",
    "true",
    "false",
    "null",
    "throw",
    "throws",
    "try",
    "catch",
    "finally",
    "break",
    "continue",
    "instanceof",
    "use",
    "with",
    "extends",
    "implements",
    "as",
    "spawn",
    "receive",
    "discard",
    "panic",
    "assert",
    "test",
    "never",
];
